-- StudioVerse multiplayer schema
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '未命名员工',
  gender text not null default 'nonbinary',
  outfit text not null default 'navy',
  expression text not null default 'calm',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.studios (
  id text primary key,
  name text not null,
  type text not null default 'content',
  owner_id uuid not null references auth.users(id) on delete cascade,
  check_in_time text not null default '09:00',
  office_layout text not null default 'default',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.studio_members (
  id uuid primary key default gen_random_uuid(),
  studio_id text not null references public.studios(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'employee',
  member_status text not null default 'pending',
  desk_id text,
  joined_at timestamptz not null default now(),
  unique(studio_id, user_id)
);

create table if not exists public.join_requests (
  id uuid primary key default gen_random_uuid(),
  studio_id text not null references public.studios(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  nickname text not null,
  profession text,
  studio_type text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id),
  unique(studio_id, user_id)
);

create table if not exists public.member_states (
  user_id uuid not null references auth.users(id) on delete cascade,
  studio_id text not null references public.studios(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key(user_id, studio_id)
);

create table if not exists public.studio_shared_state (
  studio_id text primary key references public.studios(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  studio_id text not null references public.studios(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid references auth.users(id) on delete cascade,
  content text not null default '',
  kind text not null default 'text',
  created_at timestamptz not null default now()
);

create table if not exists public.meetings (
  id uuid primary key default gen_random_uuid(),
  studio_id text not null references public.studios(id) on delete cascade,
  creator_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  meeting_time text not null,
  meeting_date date not null default current_date,
  status text not null default 'scheduled',
  attendees jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles(id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'nickname', '未命名员工'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_studio_owner(target_studio text)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists(select 1 from public.studios where id = target_studio and owner_id = auth.uid());
$$;

create or replace function public.is_studio_member(target_studio text)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists(select 1 from public.studio_members where studio_id = target_studio and user_id = auth.uid() and member_status = 'approved');
$$;

alter table public.profiles enable row level security;
alter table public.studios enable row level security;
alter table public.studio_members enable row level security;
alter table public.join_requests enable row level security;
alter table public.member_states enable row level security;
alter table public.studio_shared_state enable row level security;
alter table public.messages enable row level security;
alter table public.meetings enable row level security;

drop policy if exists profiles_self_select on public.profiles;
create policy profiles_self_select on public.profiles for select using (id = auth.uid());
drop policy if exists profiles_self_insert on public.profiles;
create policy profiles_self_insert on public.profiles for insert with check (id = auth.uid());
drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists studios_authenticated_select on public.studios;
create policy studios_authenticated_select on public.studios for select to authenticated using (true);
drop policy if exists studios_owner_insert on public.studios;
create policy studios_owner_insert on public.studios for insert to authenticated with check (owner_id = auth.uid());
drop policy if exists studios_owner_update on public.studios;
create policy studios_owner_update on public.studios for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());

drop policy if exists members_select on public.studio_members;
create policy members_select on public.studio_members for select to authenticated using (user_id = auth.uid() or public.is_studio_owner(studio_id) or public.is_studio_member(studio_id));
drop policy if exists members_owner_insert on public.studio_members;
create policy members_owner_insert on public.studio_members for insert to authenticated with check (public.is_studio_owner(studio_id));
drop policy if exists members_owner_update on public.studio_members;
create policy members_owner_update on public.studio_members for update to authenticated using (public.is_studio_owner(studio_id)) with check (public.is_studio_owner(studio_id));

drop policy if exists requests_select on public.join_requests;
create policy requests_select on public.join_requests for select to authenticated using (user_id = auth.uid() or public.is_studio_owner(studio_id));
drop policy if exists requests_self_insert on public.join_requests;
create policy requests_self_insert on public.join_requests for insert to authenticated with check (user_id = auth.uid());
drop policy if exists requests_owner_update on public.join_requests;
create policy requests_owner_update on public.join_requests for update to authenticated using (public.is_studio_owner(studio_id)) with check (public.is_studio_owner(studio_id));

drop policy if exists member_states_select on public.member_states;
create policy member_states_select on public.member_states for select to authenticated using (user_id = auth.uid() or public.is_studio_owner(studio_id) or public.is_studio_member(studio_id));
drop policy if exists member_states_self_upsert on public.member_states;
create policy member_states_self_upsert on public.member_states for insert to authenticated with check (user_id = auth.uid());
drop policy if exists member_states_self_update on public.member_states;
create policy member_states_self_update on public.member_states for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists shared_state_select on public.studio_shared_state;
create policy shared_state_select on public.studio_shared_state for select to authenticated using (public.is_studio_member(studio_id) or public.is_studio_owner(studio_id));
drop policy if exists shared_state_owner_insert on public.studio_shared_state;
create policy shared_state_owner_insert on public.studio_shared_state for insert to authenticated with check (public.is_studio_owner(studio_id));
drop policy if exists shared_state_owner_update on public.studio_shared_state;
create policy shared_state_owner_update on public.studio_shared_state for update to authenticated using (public.is_studio_owner(studio_id)) with check (public.is_studio_owner(studio_id));

drop policy if exists messages_member_select on public.messages;
create policy messages_member_select on public.messages for select to authenticated using (public.is_studio_member(studio_id) or public.is_studio_owner(studio_id));
drop policy if exists messages_member_insert on public.messages;
create policy messages_member_insert on public.messages for insert to authenticated with check (sender_id = auth.uid() and (public.is_studio_member(studio_id) or public.is_studio_owner(studio_id)));

drop policy if exists meetings_member_select on public.meetings;
create policy meetings_member_select on public.meetings for select to authenticated using (public.is_studio_member(studio_id) or public.is_studio_owner(studio_id));
drop policy if exists meetings_member_insert on public.meetings;
create policy meetings_member_insert on public.meetings for insert to authenticated with check (creator_id = auth.uid() and (public.is_studio_member(studio_id) or public.is_studio_owner(studio_id)));
drop policy if exists meetings_creator_update on public.meetings;
create policy meetings_creator_update on public.meetings for update to authenticated using (creator_id = auth.uid() or public.is_studio_owner(studio_id)) with check (creator_id = auth.uid() or public.is_studio_owner(studio_id));
